### ISSUE TITLE
NOT A BUG

### ISSUE THREAD

**Issue by TlYPN** [devin-monro/devyn-backitems#10]
Possibly add a check for entering / exiting a vehicle

if players enters a vehicle it removes the prop (stop the possibility of a tornado) 
and add a loop to keep it off
then if the player exists the vehicle it sticks it back on

**Comment by fourztL** [comment]
u need to add ispedinanyvehicle ... i try to upload my edit o send pr to creator

**Comment by KrnkTV** [comment]
any fix for that ?
