### ISSUE TITLE
weapons disappear with reloadskin, or job clothing

### ISSUE THREAD

**Issue by SmithyDevelopment** [devin-monro/devyn-backitems#16]
when changing clothing, or using the illenium-appearance reloadskin command, everything falls off the characters back.
I tried adding the TriggerEvent("backitems:displayItems", true)
into the scripts to combat this but it didnt work.

**Comment by CoZmoTheGod** [comment]
Edit client.lua around line 856

RegisterNetEvent('fivem-appearance:client:reloadSkin', function()
    if InCooldown() or CheckPlayerMeta() then
        QBCore.Functions.Notify("You cannot use reloadskin right now", "error")
        return
    end

    reloadSkinTimer = GetGameTimer()
    local playerPed = PlayerPedId()
    local health = GetEntityHealth(playerPed)
    local maxhealth = GetEntityMaxHealth(playerPed)
    local armour = GetPedArmour(playerPed)

    QBCore.Functions.TriggerCallback('fivem-appearance:server:getAppearance', function(appearance)
        if not appearance then
            return
        end
        exports[resourceName]:setPlayerAppearance(appearance)
        if Config.PersistUniforms then
            TriggerServerEvent("fivem-appearance:server:syncUniform", nil)
        end
        playerPed = PlayerPedId()
        SetPedMaxHealth(playerPed, maxhealth)
        Wait(1000) -- Safety Delay
        SetEntityHealth(playerPed, health)
        SetPedArmour(playerPed, armour)
        ResetRechargeMultipliers()
        TriggerEvent("backitems:displayItems", false)
        TriggerEvent("backitems:displayItems", true)
    end)
end)

**Comment by theenack** [comment]
I can confirm this fix works. Thank you for the great find!
