### ISSUE TITLE
people flying in sky when getting in vehicle

### ISSUE THREAD

**Issue by Nick5M420** [devin-monro/devyn-backitems#2]
randomly this causes players to do that tornado feature when entering cars and way to stop that from happening

**Comment by ARSSANTO** [comment]
disable collision

**Comment by ARSSANTO** [comment]
local function createBackItem(item)
    if not CurrentBackItems[item] then
        if Config.ItemConfig[item] then
            local i = Config.ItemConfig[item]
            local model = i['model']
            local ped = PlayerPedId()
            local bone = GetPedBoneIndex(ped, i['back_bone'])
            RequestModel(model)
            while not HasModelLoaded(model) do
                Wait(10)
            end
            SetModelAsNoLongerNeeded(model)
            CurrentBackItems[item] = CreateObject(GetHashKey(model), 1.0, 1.0, 1.0, true, true, false)
            local y = i['y']
            if QBCore.Functions.GetPlayerData().charinfo.gender == 1 then y = y + 0.035 end
            AttachEntityToEntity(CurrentBackItems[item], ped, bone, i['x'], y, i['z'], i['x_rotation'], i['y_rotation'], i['z_rotation'], 0, 1, 0, 1, 0, 1)
            SetEntityCompletelyDisableCollision(CurrentBackItems[item], false, true)
        end
    end
end  


Like this

**Comment by darktrovx** [comment]
Merged update to fix this issue.
