### ISSUE TITLE
weapon not showing on spawn

### ISSUE THREAD

**Issue by KingRyuShin** [devin-monro/devyn-backitems#5]
Yes, i followed the readme, everything is setup.. but on spawn, the weapon doesn't show up until i use them
![image](https://user-images.githubusercontent.com/42899923/163738963-93851bb2-9531-46d7-aa29-23f19be11f71.png)

![image](https://user-images.githubusercontent.com/42899923/163738945-99747ded-a07c-4aaf-bd44-bb8ad3951558.png)
![image](https://user-images.githubusercontent.com/42899923/163738975-58931152-97eb-4f72-89a3-0678ad3be364.png)

**Comment by TarikSogukpinar** [comment]
I had the same problem but it didn't work in this trigger, I'm using qb-clothing
